# Generated by Django 3.1.1 on 2020-09-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('fund_id', models.AutoField(primary_key=True, serialize=False)),
                ('fund_code', models.CharField(default=None, max_length=32, null=True, verbose_name='基金代码')),
                ('fund_name', models.CharField(default=None, max_length=32, null=True, verbose_name='基金名称')),
                ('fund_type', models.CharField(default=None, max_length=32, null=True, verbose_name='基金类型')),
                ('fund_date', models.DateTimeField(default=None, null=True, verbose_name='日期')),
                ('unit_net_worth', models.CharField(default=None, max_length=16, null=True, verbose_name='单位净值')),
                ('total_net_worth', models.CharField(default=None, max_length=16, null=True, verbose_name='累计净值')),
                ('growth_rate', models.CharField(default=None, max_length=16, null=True, verbose_name='日增长率')),
                ('six_month', models.CharField(default=None, max_length=16, null=True, verbose_name='近六个月')),
                ('one_year', models.CharField(default=None, max_length=16, null=True, verbose_name='近一年')),
                ('fund_money', models.CharField(default=None, max_length=16, null=True, verbose_name='基金规模')),
                ('fund_manager', models.CharField(default=None, max_length=16, null=True, verbose_name='基金经理')),
                ('buy_status', models.CharField(default=None, max_length=16, null=True, verbose_name='申购状态')),
                ('handling_fee', models.CharField(default=None, max_length=16, null=True, verbose_name='手续费')),
            ],
            options={
                'verbose_name_plural': '基金信息',
                'db_table': 'fund',
            },
        ),
    ]
