# Generated by Django 3.1.1 on 2020-09-22 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200922_2303'),
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='company_code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
