# Generated by Django 3.1.1 on 2020-09-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_auto_20200926_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='fund_date',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='日期'),
        ),
    ]
