# Generated by Django 3.1.1 on 2020-09-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_auto_20200926_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='buy_status',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='申购状态'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_date',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_manager',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='基金经理'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_money',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='基金规模'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_name',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='基金名称'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='fund_type',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='基金类型'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='growth_rate',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='日增长率'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='handling_fee',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='手续费'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='one_year',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='近一年'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='six_month',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='近六个月'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='total_net_worth',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='累计净值'),
        ),
        migrations.AlterField(
            model_name='fund',
            name='unit_net_worth',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='单位净值'),
        ),
    ]
