# Generated by Django 3.1.1 on 2020-11-11 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fund', '0005_auto_20200926_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundStockShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proportion', models.CharField(default=None, max_length=128, null=True, verbose_name='持仓占比')),
                ('deadline_date', models.DateTimeField(default=None, null=True, verbose_name='持仓截止日期')),
                ('crawl_time', models.DateTimeField(default=None, null=True, verbose_name='抓取时间')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
            ],
            options={
                'verbose_name_plural': '股票持仓',
                'db_table': 'fund_stock',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='股票代码')),
                ('stock_name', models.CharField(default=None, max_length=128, null=True, verbose_name='股票名称')),
                ('exchange_code', models.CharField(default=None, max_length=128, null=True, verbose_name='交易所')),
                ('fluctuation', models.CharField(default=None, max_length=128, null=True, verbose_name='涨跌幅')),
                ('crawl_time', models.DateTimeField(default=None, null=True, verbose_name='抓取时间')),
                ('fund_stock_ship', models.ManyToManyField(through='stock.FundStockShip', to='fund.Fund')),
            ],
            options={
                'verbose_name_plural': '股票信息',
                'db_table': 'stock',
            },
        ),
        migrations.AddField(
            model_name='fundstockship',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock'),
        ),
    ]
