# Generated by Django 3.1.1 on 2020-11-12 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_auto_20200926_2226'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundFundShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_fund_code', models.CharField(default=None, max_length=128, null=True, verbose_name='关联基金代码')),
                ('related_fund_name', models.CharField(default=None, max_length=128, null=True, verbose_name='关联基金名称')),
                ('proportion', models.CharField(default=None, max_length=128, null=True, verbose_name='持仓占比')),
                ('fluctuation', models.CharField(default=None, max_length=128, null=True, verbose_name='涨跌幅')),
                ('deadline_date', models.DateTimeField(default=None, null=True, verbose_name='持仓截止日期')),
                ('crawl_time', models.DateTimeField(default=None, null=True, verbose_name='抓取时间')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund.fund')),
            ],
            options={
                'verbose_name_plural': '基金信息',
                'db_table': 'fund_fund',
            },
        ),
    ]
