version: '3'
services:
  web:
    build: .
    container_name: fund_server
    restart: always
    volumes:
      - '.:/workspace'
    ports:
      - '8000:8000'
    command: bash -c "uwsgi --ini /workspace/uwsgi.ini"
