# Generated by Django 3.1.1 on 2020-09-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(default=None, max_length=16, null=True, verbose_name='公司编码')),
                ('company_name', models.CharField(default=None, max_length=32, null=True, verbose_name='公司名称')),
                ('establish_date', models.DateTimeField(default=None, null=True, verbose_name='公司成立时间')),
                ('company_star', models.CharField(default=None, max_length=16, null=True, verbose_name='公司星级')),
                ('company_money', models.CharField(default=None, max_length=16, null=True, verbose_name='管理资金')),
                ('latest_date', models.DateTimeField(default=None, null=True, verbose_name='资金规模最近更新时间')),
                ('fund_count', models.CharField(default=None, max_length=16, null=True, verbose_name='基金数量')),
                ('fund_manger_count', models.CharField(default=None, max_length=16, null=True, verbose_name='基金经理数量')),
            ],
            options={
                'verbose_name_plural': '基金公司',
                'db_table': 'company',
            },
        ),
    ]
