# Generated by Django 3.1.1 on 2020-09-22 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='fund_manger_count',
            new_name='fund_manager_count',
        ),
    ]
