# Generated by Django 3.1.1 on 2020-09-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200922_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='latest_date',
            field=models.CharField(default=None, max_length=16, null=True, verbose_name='资金规模最近更新时间'),
        ),
    ]
