# Generated by Django 3.1.1 on 2020-09-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200922_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='公司编码'),
        ),
    ]
