# Generated by Django 3.1.1 on 2020-09-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20200922_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='crawl_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='抓取时间'),
        ),
    ]
