# Generated by Django 3.1.1 on 2020-09-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_company_crawl_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_money',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='管理资金'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_star',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='公司星级'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fund_count',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='基金数量'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fund_manager_count',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='基金经理数量'),
        ),
        migrations.AlterField(
            model_name='company',
            name='latest_date',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='资金规模最近更新时间'),
        ),
    ]
